name: tarkov-quests

services:
  backend:
    build: ../backend
    volumes:
      - ./data/prod:/app/data
    ports:
      - "3000:3000"
  frontend:
    build: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
